### ISSUE TITLE
pandas >= 0.23.0 required

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Genie#215]
https://github.com/Sage-Bionetworks/Genie/blob/master/setup.py#L14

Tried running in a Docker container (https://github.com/Sage-Bionetworks/veoibd-validation-docker/blob/master/Dockerfile#L1-L14). Installs `python3-pandas` using system package manager, which gets `pandas==0.22.0`. This is not sufficient, as [this function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.append.html) requires `>=0.23.0`:

```
Traceback (most recent call last):
  File "/usr/local/bin/input_to_database.py", line 246, in <module>
    thread=args.thread)
  File "/usr/local/bin/input_to_database.py", line 147, in main
    raise e
  File "/usr/local/bin/input_to_database.py", line 131, in main
    thread=thread, format_registry=format_registry)
  File "/usr/local/lib/python3.6/dist-packages/genie/input_to_database.py", line 751, in center_input_to_database
    testing, oncotree_link, format_registry)
  File "/usr/local/lib/python3.6/dist-packages/genie/input_to_database.py", line 694, in validation
    error_tracker_table)
  File "/usr/local/lib/python3.6/dist-packages/genie/input_to_database.py", line 598, in update_status_and_error_tables
    ["id"], to_delete=True)
  File "/usr/local/lib/python3.6/dist-packages/genie/process_functions.py", line 762, in updateDatabase
    allupdates = allupdates.append(to_append_rows, sort=False)
TypeError: append() got an unexpected keyword argument 'sort'
```

**Comment by thomasyu888** [comment]
I use pip3 to install.
