### ISSUE TITLE
Fix dashboard_markdown_template

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/Genie#258]
```python
  cannot open file 'dashboardTemplate.Rmd': No such file or directory
Execution halted
Traceback (most recent call last):
  File "bin/database_to_staging.py", line 306, in <module>
    skip_mutationsincis=args.skipMutationsInCis)
  File "bin/database_to_staging.py", line 229, in main
    subprocess.check_call(dashboard_markdown_html_commands)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['Rscript', '/home/tyu/Genie/bin/../genie/dashboard_markdown_generator.R', '8.2-consortium']' returned non-zero exit status 1.
```

**Comment by thomasyu888** [comment]
#259
