### ISSUE TITLE
Deal with non-ascii characters

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/Genie#343]
UHN Fusion file
```

2020-08-20T15:06:27.338-07:00 | File "bin/database_to_staging.py", line 366, in <module>
-- | --
  | 2020-08-20T15:06:27.338-07:00 | skip_mutationsincis=args.skipMutationsInCis)
  | 2020-08-20T15:06:27.338-07:00 | File "bin/database_to_staging.py", line 187, in main
  | 2020-08-20T15:06:27.338-07:00 | genie_pass=genie_pass)
  | 2020-08-20T15:06:27.338-07:00 | File "/root/Genie/genie/database_to_staging.py", line 1395, in stagingToCbio
  | 2020-08-20T15:06:27.338-07:00 | CENTER_MAPPING_DF)
  | 2020-08-20T15:06:27.338-07:00 | File "/root/Genie/genie/database_to_staging.py", line 595, in store_fusion_files
  | 2020-08-20T15:06:27.338-07:00 | fusionFile.write(fusionText)
  | 2020-08-20T15:06:27.338-07:00 | UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 2401565: ordinal not in range(128)


```
CHOP Assay information file
```

2020-08-20T02:18:55.468-07:00CopyUnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 281: ordinal not in range(128) | UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 281: ordinal not in range(128)
-- | --
  | 2020-08-20T02:18:55.468-07:00 | During handling of the above exception, another exception occurred:
  | 2020-08-20T02:18:55.468-07:00 | Traceback (most recent call last):
  | 2020-08-20T02:18:55.468-07:00 | File "bin/input_to_database.py", line 170, in <module>
  | 2020-08-20T02:18:55.468-07:00 | genie_annotation_pkg=args.genie_annotation_pkg)
  | 2020-08-20T02:18:55.468-07:00 | File "bin/input_to_database.py", line 95, in main
  | 2020-08-20T02:18:55.468-07:00 | genie_annotation_pkg=genie_annotation_pkg
  | 2020-08-20T02:18:55.468-07:00 | File "/root/Genie/genie/input_to_database.py", line 851, in center_input_to_database
  | 2020-08-20T02:18:55.468-07:00 | genome_nexus_pkg=genie_annotation_pkg)
  | 2020-08-20T02:18:55.468-07:00 | File "/root/Genie/genie/input_to_database.py", line 344, in processfiles
  | 2020-08-20T02:18:55.468-07:00 | databaseToSynIdMappingDf=databaseToSynIdMappingDf
  | 2020-08-20T02:18:55.468-07:00 | File "/root/Genie/genie/example_filetype_format.py", line 121, in process
  | 2020-08-20T02:18:55.468-07:00 | path_or_df = self.read_file([filePath])
  | 2020-08-20T02:18:55.468-07:00 | File "/root/Genie/genie/example_filetype_format.py", line 51, in read_file
  | 2020-08-20T02:18:55.468-07:00 | df = self._get_dataframe(filePathList)
  | 2020-08-20T02:18:55.468-07:00 | File "/root/Genie/genie/assay.py", line 81, in _get_dataframe
  | 2020-08-20T02:18:55.468-07:00 | "assay_information.yaml: Can't read in your file. "
  | 2020-08-20T02:18:55.468-07:00 | ValueError: assay_information.yaml: Can't read in your file. Please make sure the file is a correctly formatted yaml


```

**Comment by thomasyu888** [comment]
I manually updated those files to not have ascii characters, but the code should perhaps try to catch these.
