### ISSUE TITLE
Keyring version not compatible with python 3.10

### ISSUE THREAD

**Issue by jakevc** [Sage-Bionetworks/Genie#412]
Insatlled genie in new conda environment with python3.10

```
conda create -n genie python
conda activate genie
pip install aacrgenie
```

The tool panics with the following error from the keyring backend:

```
ImportError: cannot import name 'Callable' from 'collections' 
```

Turns out whatever version of keyring is not compatible with python3.10:

```
python -c "import keyring as package; print(package.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jake.vancampenprovidence.org/miniconda3/envs/genie/lib/python3.10/site-packages/keyring/__init__.py", line 3, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/Users/jake.vancampenprovidence.org/miniconda3/envs/genie/lib/python3.10/site-packages/keyring/core.py", line 13, in <module>
    from . import backend
  File "/Users/jake.vancampenprovidence.org/miniconda3/envs/genie/lib/python3.10/site-packages/keyring/backend.py", line 13, in <module>
    from .util import properties
  File "/Users/jake.vancampenprovidence.org/miniconda3/envs/genie/lib/python3.10/site-packages/keyring/util/properties.py", line 1, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/Users/jake.vancampenprovidence.org/miniconda3/envs/genie/lib/python3.10/collections/__init__.py)
```

Upgraded to keyring latest and solved the problem:

```
pip install -I keyring==23.2.1
genie -v
genie 12.5.0
```

This is due to a change in the python standard library I guess specific to 3.10: https://docs.python.org/3/library/collections.abc.html, because downgrading to python3.9 resolves.

**Comment by jakevc** [comment]
Interestingly, SynapsePythonClient is stable using the older keyring and python3.10...

**Comment by thomasyu888** [comment]
Thanks @jakevc.  I'm going to leave this ticket open, but python 3.10 is untested currently.  Please use older versions of python for now.
