### ISSUE TITLE
Validation of clinical files fails with numpy error

### ISSUE THREAD

**Issue by jakevc** [Sage-Bionetworks/Genie#426]
I have encountered the following error when performing validation on patient and sample clinical files.

```
docker run -v $(pwd):/data --rm sagebionetworks/genie genie --syn_user ###### --syn_pass ############ validate /data/data_clinical_supp_patient_PROV.txt /data/data_clinical_supp_sample_PROV.txt PROV

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
INFO:genie.example_filetype_format:VALIDATING data_clinical_supp_sample_PROV.txt
Traceback (most recent call last):
  File "/usr/local/bin/genie", line 33, in <module>
    sys.exit(load_entry_point('aacrgenie', 'console_scripts', 'genie')())
  File "/root/Genie/genie/__main__.py", line 149, in main
    args.func(syn, args)
  File "/root/Genie/genie/validate.py", line 260, in _perform_validate
    valid, message = validator.validate_single_file(**mykwargs)
  File "/root/Genie/genie/validate.py", line 91, in validate_single_file
    valid, errors, warnings = validator.validate(filePathList=filepathlist,
  File "/root/Genie/genie/example_filetype_format.py", line 173, in validate
    errors, warnings = self._validate(df, **mykwargs)
  File "/root/Genie/genie_registry/clinical.py", line 833, in _validate
    if not sample_class_vals.isin(['Tumor', 'cfDNA']).all():
AttributeError: 'numpy.ndarray' object has no attribute 'isin'
```

**Comment by thomasyu888** [comment]
Thanks @jakevc for filing the error. I have fixed this - forgot to add tests the first time around.
